export const SET_INPUT = 'SET_INPUT';
export const SET_LANGUAGE_BY_CONTROLLER_ID = 'SET_LANGUAGE_BY_CONTROLLER_ID';
export const ADD_TRANSLATION = 'ADD_TRANSLATION';
export const SET_AVALIABLE_LANGUAGES = 'SET_AVALIABLE_LANGUAGES';

export const GET_DICTIONARY_LOOKUP = 'GET_DICTIONARY_LOOKUP';
export const GET_TEXT_TRANSLATE = 'GET_TEXT_TRANSLATE';

export const INCREMENT_CURRENT_TRANSLATION_ID =
    'INCREMENT_CURRENT_TRANSLATION_ID';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';

export const TRANSLATE_ACTION = 'TRANSLATE_ACTION';
export const SWAP_LANGUAGES_ACTION = 'SWAP_LANGUAGES_ACTION';
