export const SET_NEW_TRANSLATION_ID_ACTION = 'SET_NEW_TRANSLATION_ID_ACTION';
export const TRANSLATE_ACTION = 'TRANSLATE_ACTION';
export const SWAP_LANGUAGES_ACTION = 'SWAP_LANGUAGES_ACTION';
export const FETCH_AVALIABLE_LANGUAGES_ACTION = 'FETCH_AVALIABLE_LANGUAGES_ACTION';
export const FETCH_AVALIABLE_LANGUAGES_PAIRS_ACTION =
    'FETCH_AVALIABLE_LANGUAGES_PAIRS_ACTION';
export const TRY_TO_LOAD_EXISTING_TRANSLATION_ACTION =
    'TRY_TO_LOAD_EXISTING_TRANSLATION_ACTION';
export const ERASE_ALL_DATA_ACTION = 'ERASE_ALL_DATA_ACTION';
export const INCREMENT_INTERFACE_SIZE_ACTION = 'INCREMENT_INTERFACE_SIZE_ACTION';
